### ISSUE TITLE
Layout broken in HA 2025.1.0

### ISSUE THREAD

**Issue by adorobis** [mweimerskirch/lovelace-hacomfoairmqtt#4]
Hello,
Hope you are still using it and you could help fixing the card which is not displayed properly in HA 2025.1.0:
![image](https://github.com/user-attachments/assets/9c0d2611-86fe-4898-b8ae-ac0a2543b213)
Not sure what is causing it...

**Comment by mweimerskirch** [comment]
Yes, I'm still using the card myself and I'm having the same issue since I updated last weekend.

This is caused by this PR in the home assistant frontend: https://github.com/home-assistant/frontend/pull/23165
More specifically file src/components/ha-svg-icon.ts line 11.
It seems that a lot of code was changed to eliminate warnings in ESLint. In the process, “attribute: false” was added to many properties, which means that these properties are no longer recognized when used as attributes.

The "ha-svg-icon" component is used in this line and the viewbox attribute is no longer recognized:
https://github.com/mweimerskirch/lovelace-hacomfoairmqtt/blob/main/src/hacomfoairmqtt-card.ts#L311

Unfortunately, I didn't have time yet to open a proper issue on the HomeAssistant frontend project and I won't have time before next weekend. Feel free to do so.

On the other hand, the ha-svg-icon could probably be replaced with a plain "svg" tag. Not sure why I used that component in the first place, but this was my first (and only) Home Assistant frontend card I wrote.

**Comment by adorobis** [comment]
Many thanks for quick reply.  I'm not really understanding much from that so I'll wait for you. No rush from my side, take your time :)

**Comment by Lamarqe** [comment]
Thank you! 

Great so see that others also use this card and even identified the source of the problem. ❤️

**Comment by mweimerskirch** [comment]
The display issue should be fixed.

**Comment by adorobis** [comment]
Perfect, many thanks! Just had to clear cached data to make it work

**Comment by Boto11** [comment]
Hello, on the mobile app, the card is still not displaying properly.
Could it be a setting on my side?

**Comment by mweimerskirch** [comment]
> Hello, on the mobile app, the card is still not displaying properly. Could it be a setting on my side?

Try clearing your app cache.

**Comment by Boto11** [comment]
Unfortunately, clearing the app didn’t help.

**Comment by mweimerskirch** [comment]
> Unfortunately, clearing the app didn’t help.

Describe what you did to clear the cache.

**Comment by Boto11** [comment]
It works now, even though I didn't do anything else.

Thank you very much!
